name: 📚 Mise à jour de la documentation
description: Améliorer ou mettre à jour la documentation du projet.
title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Mise à jour de la documentation
        Suggérer des changements ou ajouts à la docs.
  - type: textarea
    id: current-docs
    attributes:
      label: Documentation actuelle
      description: Décrivez la documentation existante qui nécessite une mise à jour.
      placeholder: "Lien vers la section ou le fichier..."
    validations:
      required: true
  - type: textarea
    id: proposed-changes
    attributes:
      label: Changements proposés
      description: Que faut-il ajouter, supprimer ou modifier ?
      placeholder: "Suggestions détaillées..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Contexte supplémentaire
      description: Pourquoi cette mise à jour est-elle nécessaire ? Références ?
      placeholder: "Fournir du contexte..."
  - type: checkboxes
    id: terms
    attributes:
      label: Liste de contrôle
      options:
        - label: J'ai vérifié les issues existantes
          required: true
        - label: J'ai lu les directives de contribution
          required: true
        - label: J'accepte de suivre le code de conduite du projet
          required: true
