name: ✨ Demande de fonctionnalité
description: Suggérer une nouvelle fonctionnalité.
title: "[Fonctionnalité] "
labels: ["fonctionnalité"]
body:
  - type: markdown
    attributes:
      value: |
        ## Demande de fonctionnalité
        Décrivez la fonctionnalité que vous aimeriez voir.
  - type: textarea
    id: problem
    attributes:
      label: Votre demande de fonctionnalité est-elle liée à un problème ?
      description: Une description claire du problème que cette fonctionnalité résout.
      placeholder: "Je suis toujours frustré quand..."
  - type: textarea
    id: solution
    attributes:
      label: Décrivez la solution souhaitée
      description: Que voulez-vous qu'il se passe ?
      placeholder: "Une description claire..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Décrivez les alternatives que vous avez envisagées
      description: Des solutions ou fonctionnalités alternatives ?
      placeholder: "Autres approches..."
  - type: checkboxes
    id: terms
    attributes:
      label: Liste de contrôle
      options:
        - label: J'ai vérifié les issues existantes
          required: true
        - label: J'ai lu les directives de contribution
          required: true
        - label: J'accepte de suivre le code de conduite du projet
          required: true
