name: 🔒 Signaler une vulnérabilité de sécurité
description: Signaler en privé une vulnérabilité de sécurité.
title: "[Sécurité] "
labels: ["sécurité"]
body:
  - type: markdown
    attributes:
      value: |
        ## Rapport de vulnérabilité de sécurité
        Utilisez ceci pour signaler des vulnérabilités. Pour les rapports privés, considérez utiliser les avis de sécurité de GitHub.
  - type: textarea
    id: vulnerability-description
    attributes:
      label: Description de la vulnérabilité
      description: Une description claire de la vulnérabilité.
      placeholder: "Détails sans exposer d'informations sensibles..."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Étapes pour reproduire
      description: Comment pouvons-nous la reproduire ?
      placeholder: "Étape 1 : ..."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact potentiel
      description: Que pourrait-on exploiter ?
      placeholder: "Niveau de gravité, composants affectés..."
  - type: textarea
    id: suggested-fix
    attributes:
      label: Correction suggérée
      description: Idées pour la mitigation ?
      placeholder: "Suggestions optionnelles..."
  - type: checkboxes
    id: terms
    attributes:
      label: Liste de contrôle
      options:
        - label: J'ai vérifié les avis de sécurité existants
          required: true
        - label: J'ai lu les directives de contribution
          required: true
        - label: J'accepte de suivre le code de conduite du projet
          required: true
